from application import db
from application.models import Ideas, Tags
db.drop_all()
db.create_all()
t1 = Tags(name = "Landscape")
t2 = Tags(name = "Portrait")
t3 = Tags(name = "Food")
t4 = Tags(name = "Wildlife")
t5 = Tags(name = "Travel")
i1 = Ideas(title = "World Wonder", description = "Try and find an interesting perspective!", tag_id = "1", name = "Bradley")
i2 = Ideas(title = "Castle by water", description = "Plenty can be found, go searching!", tag_id = "1", name = "Bradley")
db.session.add(t1)
db.session.add(t2)
db.session.add(t3)
db.session.add(t4)
db.session.add(t5)
db.session.add(i1)
db.session.add(i2)
db.session.commit()